[package]
name = "pending-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "pending-tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm.workspace = true
pending-core = { path = "../pending-core" }
pending-runtime = { path = "../pending-runtime" }
ratatui.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
