[package]
name = "pending-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
chrono.workspace = true
pending-core = { path = "../pending-core" }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }
