[package]
name = "tasks-pending"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "tasks-pending"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
pending-api = { path = "../pending-api" }
pending-tui = { path = "../pending-tui" }
tokio.workspace = true
